In [11]:
import pandas as pd

In [12]:
df = pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [13]:
"""
Filter data on basis of certain required condition

"""

'\nFilter data on basis of certain required condition\n\n'

In [14]:
# provied all detail of employee whose salary between 10000 and 20000
required_salary = (df['SALARY']>=10000) & (df['SALARY']<=20000)
df[required_salary]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,2002-08-17,FI_MGR,12008,NaN,101.0,100.0
14,114,Den,Raphaely,DRAPHEAL,515.127.4561,2002-12-07,PU_MAN,11000,NaN,100.0,30.0
45,145,John,Russell,JRUSSEL,011.44.1344.429268,2004-10-01,SA_MAN,14000,0.40,100.0,80.0
46,146,Karen,Partners,KPARTNER,011.44.1344.467268,2005-01-05,SA_MAN,13500,0.30,100.0,80.0
47,147,Alberto,Errazuriz,AERRAZUR,011.44.1344.429278,2005-03-10,SA_MAN,12000,0.30,100.0,80.0
48,148,Gerald,Cambrault,GCAMBRAU,011.44.1344.619268,2007-10-15,SA_MAN,11000,0.30,100.0,80.0
49,149,Eleni,Zlotkey,EZLOTKEY,011.44.1344.429018,2008-01-29,SA_MAN,10500,0.20,100.0,80.0
50,150,Peter,Tucker,PTUCKER,011.44.1344.129268,2005-01-30,SA_REP,10000,0.30,145.0,80.0
56,156,Janette,King,JKING,011.44.1345.429268,2004-01-30,SA_REP,10000,0.35,146.0,80.0
62,162,Clara,Vishney,CVISHNEY,011.44.1346.129268,2005-11-11,SA_REP,10500,0.25,147.0,80.0
68,168,Lisa,Ozer,LOZER,011.44.1343.929268,2005-03-11,SA_REP,11500,0.25,148.0,80.0
69,169,Harrison,Bloom,HBLOOM,011.44.1343.829268,2006-03-23,SA_REP,10000,0.20,148.0,80.0
74,174,Ellen,Abel,EABEL,011.44.1644.429267,2004-05-11,SA_REP,11000,0.30,149.0,80.0
101,201,Michael,Hartstein,MHARTSTE,515.123.5555,2004-02-17,MK_MAN,13000,NaN,100.0,20.0
104,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
105,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0

In [15]:
senior_employee = df[df['SALARY'] == 6000]

if not senior_employee.empty:
    print(f"She is intelligent:\n{senior_employee}")
else:
    print("No employee has salary equal to 6000")

She is intelligent:
     EMPLOYEE_ID FIRST_NAME LAST_NAME   EMAIL  PHONE_NUMBER   HIRE_DATE  \
4            104      Bruce     Ernst  BERNST  590.423.4568  2007-05-21
102          202        Pat       Fay    PFAY  603.123.6666  2005-08-17

      JOB_ID  SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID
4    IT_PROG    6000             NaN       103.0           60.0
102   MK_REP    6000             NaN       201.0           20.0

In [16]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [17]:
# provide information between of employee ,salary between 5000,8000
emp_sal = (df['SALARY'] >= 5000) & (df['SALARY'] <= 8000)
df[emp_sal]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,2005-09-30,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,2006-03-07,FI_ACCOUNT,7800,NaN,108.0,100.0
13,113,Luis,Popp,LPOPP,515.124.4567,2007-12-07,FI_ACCOUNT,6900,NaN,108.0,100.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,2004-07-18,ST_MAN,8000,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,2003-05-01,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,2005-10-10,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,2007-11-16,ST_MAN,5800,NaN,100.0,50.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,2006-03-30,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,2006-12-09,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,2007-11-23,SA_REP,7000,0.15,145.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,2005-03-10,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,2005-12-15,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,2006-11-03,SA_REP,7000,0.25,146.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,2008-01-24,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2008-02-23,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,2008-03-24,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,2008-04-21,SA_REP,6200,0.10,147.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2007-02-23,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,2007-03-24,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,2008-04-21,SA_REP,6100,0.10,148.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,2007-05-24,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,2008-01-04,SA_REP,6200,0.10,149.0,80.0
102,202,Pat,Fay,PFAY,603.123.6666,2005-08-17,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0

# between(5000, 10000) is just a shorter way to write:

greater than or equal to 5000
and less than or equal to 10000

In [18]:
# alternative code without using between to find salary between 4000 to 8000

df[(df['SALARY']>=4000)&(df['SALARY']<=8000)]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,NaN,103.0,60.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,2005-09-30,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,2006-03-07,FI_ACCOUNT,7800,NaN,108.0,100.0
13,113,Luis,Popp,LPOPP,515.124.4567,2007-12-07,FI_ACCOUNT,6900,NaN,108.0,100.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,2004-07-18,ST_MAN,8000,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,2003-05-01,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,2005-10-10,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,2007-11-16,ST_MAN,5800,NaN,100.0,50.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,2006-03-30,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,2006-12-09,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,2007-11-23,SA_REP,7000,0.15,145.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,2005-03-10,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,2005-12-15,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,2006-11-03,SA_REP,7000,0.25,146.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,2008-01-24,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2008-02-23,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,2008-03-24,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,2008-04-21,SA_REP,6200,0.10,147.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2007-02-23,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,2007-03-24,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,2008-04-21,SA_REP,6100,0.10,148.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,2007-05-24,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,2008-01-04,SA_REP,6200,0.10,149.0,80.0
84,184,Nandita,Sarchand,NSARCHAN,650.509.1876,2004-01-27,SH_CLERK,4200,NaN,121.0,50.0
85,185,Alexis,Bull,ABULL,650.509.2876,2005-02-20,SH_CLERK,4100,NaN,121.0,50.0
92,192,Sarah,Bell,SBELL,650.501.1876,2004-02-04,SH_CLERK,4000,NaN,123.0,50.0
100,200,Jennifer,Whalen,JWHALEN,515.123.4444,2003-09-17,AD_ASST,4400,NaN,101.0,10.0
102,202,Pat,Fay,PFAY,603.123.6666,2005-08-17,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0

## same above thing perform by using between function
###df[df['column_name'].between(range)]

In [19]:
# between and isin - for pandas in conditional filtering (assignment )

df[df['SALARY'].between(4000, 8000)]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,NaN,103.0,60.0
11,111,Ismael,Sciarra,ISCIARRA,515.124.4369,2005-09-30,FI_ACCOUNT,7700,NaN,108.0,100.0
12,112,Jose Manuel,Urman,JMURMAN,515.124.4469,2006-03-07,FI_ACCOUNT,7800,NaN,108.0,100.0
13,113,Luis,Popp,LPOPP,515.124.4567,2007-12-07,FI_ACCOUNT,6900,NaN,108.0,100.0
20,120,Matthew,Weiss,MWEISS,650.123.1234,2004-07-18,ST_MAN,8000,NaN,100.0,50.0
22,122,Payam,Kaufling,PKAUFLIN,650.123.3234,2003-05-01,ST_MAN,7900,NaN,100.0,50.0
23,123,Shanta,Vollman,SVOLLMAN,650.123.4234,2005-10-10,ST_MAN,6500,NaN,100.0,50.0
24,124,Kevin,Mourgos,KMOURGOS,650.123.5234,2007-11-16,ST_MAN,5800,NaN,100.0,50.0
53,153,Christopher,Olsen,COLSEN,011.44.1344.498718,2006-03-30,SA_REP,8000,0.20,145.0,80.0
54,154,Nanette,Cambrault,NCAMBRAU,011.44.1344.987668,2006-12-09,SA_REP,7500,0.20,145.0,80.0
55,155,Oliver,Tuvault,OTUVAULT,011.44.1344.486508,2007-11-23,SA_REP,7000,0.15,145.0,80.0
59,159,Lindsey,Smith,LSMITH,011.44.1345.729268,2005-03-10,SA_REP,8000,0.30,146.0,80.0
60,160,Louise,Doran,LDORAN,011.44.1345.629268,2005-12-15,SA_REP,7500,0.30,146.0,80.0
61,161,Sarath,Sewall,SSEWALL,011.44.1345.529268,2006-11-03,SA_REP,7000,0.25,146.0,80.0
64,164,Mattea,Marvins,MMARVINS,011.44.1346.329268,2008-01-24,SA_REP,7200,0.10,147.0,80.0
65,165,David,Lee,DLEE,011.44.1346.529268,2008-02-23,SA_REP,6800,0.10,147.0,80.0
66,166,Sundar,Ande,SANDE,011.44.1346.629268,2008-03-24,SA_REP,6400,0.10,147.0,80.0
67,167,Amit,Banda,ABANDA,011.44.1346.729268,2008-04-21,SA_REP,6200,0.10,147.0,80.0
71,171,William,Smith,WSMITH,011.44.1343.629268,2007-02-23,SA_REP,7400,0.15,148.0,80.0
72,172,Elizabeth,Bates,EBATES,011.44.1343.529268,2007-03-24,SA_REP,7300,0.15,148.0,80.0
73,173,Sundita,Kumar,SKUMAR,011.44.1343.329268,2008-04-21,SA_REP,6100,0.10,148.0,80.0
78,178,Kimberely,Grant,KGRANT,011.44.1644.429263,2007-05-24,SA_REP,7000,0.15,149.0,NaN
79,179,Charles,Johnson,CJOHNSON,011.44.1644.429262,2008-01-04,SA_REP,6200,0.10,149.0,80.0
84,184,Nandita,Sarchand,NSARCHAN,650.509.1876,2004-01-27,SH_CLERK,4200,NaN,121.0,50.0
85,185,Alexis,Bull,ABULL,650.509.2876,2005-02-20,SH_CLERK,4100,NaN,121.0,50.0
92,192,Sarah,Bell,SBELL,650.501.1876,2004-02-04,SH_CLERK,4000,NaN,123.0,50.0
100,200,Jennifer,Whalen,JWHALEN,515.123.4444,2003-09-17,AD_ASST,4400,NaN,101.0,10.0
102,202,Pat,Fay,PFAY,603.123.6666,2005-08-17,MK_REP,6000,NaN,201.0,20.0
103,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0

## if we not required all details between range , IF you wnat specific column then we use loc function
# df.loc[df['filter_column'].between(range),[number of column which we want to extract]       ]

In [20]:
#Q-> find out first_name ,last_name and salary of employee whose salary range between 5000 to 10000
df.loc[df['SALARY'].between(5000,10000),['FIRST_NAME','LAST_NAME','SALARY']].count()

FIRST_NAME    46
LAST_NAME     46
SALARY        46
dtype: int64

## This is very important concept

In [21]:
#df.loc[df['SALARY'].between(5000, 10000)]
df.loc[df['SALARY'].between(5000, 10000), ['EMAIL', 'SALARY']] # this is very very important concept

        EMAIL  SALARY
3     AHUNOLD    9000
4      BERNST    6000
9     DFAVIET    9000
10      JCHEN    8200
11   ISCIARRA    7700
12    JMURMAN    7800
13      LPOPP    6900
20     MWEISS    8000
21     AFRIPP    8200
22   PKAUFLIN    7900
23   SVOLLMAN    6500
24   KMOURGOS    5800
50    PTUCKER   10000
51   DBERNSTE    9500
52      PHALL    9000
53     COLSEN    8000
54   NCAMBRAU    7500
55   OTUVAULT    7000
56      JKING   10000
57     PSULLY    9500
58    AMCEWEN    9000
59     LSMITH    8000
60     LDORAN    7500
61    SSEWALL    7000
63    DGREENE    9500
64   MMARVINS    7200
65       DLEE    6800
66      SANDE    6400
67     ABANDA    6200
69     HBLOOM   10000
70       TFOX    9600
71     WSMITH    7400
72     EBATES    7300
73     SKUMAR    6100
75    AHUTTON    8800
76    JTAYLOR    8600
77   JLIVINGS    8400
78     KGRANT    7000
79   CJOHNSON    6200
102      PFAY    6000
103   SMAVRIS    6500
104     HBAER   10000
106    WGIETZ    8300
107   SMAVRIS    6500
108     HBAER   10000
110    WGIETZ    8300

In [22]:
# find out the employee first_name and last_name whose department_id in range 60 to  and also  sort the salary
df.loc[(df['DEPARTMENT_ID'].between(60,90)),['FIRST_NAME','LAST_NAME','SALARY']].sort_values('SALARY')
# here condition column is department_id

      FIRST_NAME   LAST_NAME  SALARY
7          Diana     Lorentz    4200
5          David      Austin    4800
6          Valli   Pataballa    4800
4          Bruce       Ernst    6000
73       Sundita       Kumar    6100
67          Amit       Banda    6200
79       Charles     Johnson    6200
66        Sundar        Ande    6400
65         David         Lee    6800
55        Oliver     Tuvault    7000
61        Sarath      Sewall    7000
64        Mattea     Marvins    7200
72     Elizabeth       Bates    7300
71       William       Smith    7400
54       Nanette   Cambrault    7500
60        Louise       Doran    7500
59       Lindsey       Smith    8000
53   Christopher       Olsen    8000
77          Jack  Livingston    8400
76      Jonathon      Taylor    8600
75        Alyssa      Hutton    8800
58         Allan      McEwen    9000
3      Alexander      Hunold    9000
52         Peter        Hall    9000
63      Danielle      Greene    9500
51         David   Bernstein    9500
57       Patrick       Sully    9500
70        Tayler         Fox    9600
50         Peter      Tucker   10000
56       Janette        King   10000
69      Harrison       Bloom   10000
104      Hermann        Baer   10000
108      Hermann        Baer   10000
62         Clara     Vishney   10500
49         Eleni     Zlotkey   10500
74         Ellen        Abel   11000
48        Gerald   Cambrault   11000
68          Lisa        Ozer   11500
47       Alberto   Errazuriz   12000
46         Karen    Partners   13500
45          John     Russell   14000
1          Neena     Kochhar   17000
2            Lex     De Haan   17000
0         Steven        King   24000

In [23]:
df.loc[df['SALARY'].between(5000, 10000), ['FIRST_NAME', 'SALARY']] .sort_values('SALARY')
# here the condition column is salary

      FIRST_NAME  SALARY
24         Kevin    5800
4          Bruce    6000
102          Pat    6000
73       Sundita    6100
67          Amit    6200
79       Charles    6200
66        Sundar    6400
23        Shanta    6500
103        Susan    6500
107        Susan    6500
65         David    6800
13          Luis    6900
61        Sarath    7000
55        Oliver    7000
78     Kimberely    7000
64        Mattea    7200
72     Elizabeth    7300
71       William    7400
54       Nanette    7500
60        Louise    7500
11        Ismael    7700
12   Jose Manuel    7800
22         Payam    7900
20       Matthew    8000
53   Christopher    8000
59       Lindsey    8000
10          John    8200
21          Adam    8200
106      William    8300
110      William    8300
77          Jack    8400
76      Jonathon    8600
75        Alyssa    8800
3      Alexander    9000
9         Daniel    9000
52         Peter    9000
58         Allan    9000
57       Patrick    9500
51         David    9500
63      Danielle    9500
70        Tayler    9600
69      Harrison   10000
50         Peter   10000
56       Janette   10000
104      Hermann   10000
108      Hermann   10000

## loc[]
# between()
# sort_values()
# count()

In [37]:
df.loc[df['SALARY'].between(5000,10000),['FIRST_NAME','SALARY']].sort_values('SALARY').count()

FIRST_NAME    46
SALARY        46
dtype: int64

In [38]:
df['JOB_ID'].unique()

<StringArray>
[   'AD_PRES',      'AD_VP',    'IT_PROG',     'FI_MGR', 'FI_ACCOUNT',
     'PU_MAN',   'PU_CLERK',     'ST_MAN',   'ST_CLERK',     'SA_MAN',
     'SA_REP',   'SH_CLERK',    'AD_ASST',     'MK_MAN',     'MK_REP',
     'HR_REP',     'PR_REP',     'AC_MGR', 'AC_ACCOUNT']
Length: 19, dtype: str

# between() function  is give ANDing concept
# isin() function is give  OR ing concept

In [41]:
#isin()--> Checks whether a value is one of several allowed values.
# alternative code without using isin ->
df[(df['JOB_ID']=='IT_PROG')|(df['JOB_ID'] == 'FI_MGR')]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,23.0,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,23.0,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,23.0,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,23.0,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,23.0,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,2002-08-17,FI_MGR,12008,23.0,101.0,100.0

In [53]:
#show the details of employee whose job_id is 'IT_PROG'or 'FI_MGR'
df.loc[df['JOB_ID'].isin(['IT_PROG','FI_MGR'])]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,23.0,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,23.0,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,23.0,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,23.0,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,23.0,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,2002-08-17,FI_MGR,12008,23.0,101.0,100.0

In [54]:
#show the details of employee whose job_id is 'IT_PROG'or 'FI_MGR' with only column of
#  'HIRE_DATE','JOB_ID','SALARY'
df.loc[df['JOB_ID'].isin(['IT_PROG','FI_MGR']),['HIRE_DATE','JOB_ID','SALARY']]

    HIRE_DATE   JOB_ID  SALARY
3  2006-01-03  IT_PROG    9000
4  2007-05-21  IT_PROG    6000
5  2005-06-25  IT_PROG    4800
6  2006-02-05  IT_PROG    4800
7  2007-02-07  IT_PROG    4200
8  2002-08-17   FI_MGR   12008

In [58]:
#show the details of employee whose job_id is 'IT_PROG'or 'FI_MGR' with only column of
#  'HIRE_DATE','JOB_ID','SALARY' but salary should be sorted 
df.loc[(df['JOB_ID'].isin(['IT_PROG','FI_MGR']),['HIRE_DATE','JOB_ID','SALARY'])].sort_values('SALARY')

    HIRE_DATE   JOB_ID  SALARY
7  2007-02-07  IT_PROG    4200
6  2006-02-05  IT_PROG    4800
5  2005-06-25  IT_PROG    4800
4  2007-05-21  IT_PROG    6000
3  2006-01-03  IT_PROG    9000
8  2002-08-17   FI_MGR   12008

In [62]:
# list the employee whose salary between 5000 to 10000 and who must be work in HR_REP job
df[(df['SALARY'].between(5000,10000)) & (df['JOB_ID']=='HR_REP')]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,23.0,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,23.0,101.0,40.0

In [65]:

# find employee who works under department 60 and 90 only
depart_under = (df['DEPARTMENT_ID']==60)|(df['DEPARTMENT_ID']==90)
df[depart_under]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,23.0,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,23.0,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,23.0,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,23.0,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,23.0,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,23.0,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,23.0,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,23.0,103.0,60.0

# using both isin and between both function in same query

In [70]:
# above same thingdone by using isin function
df[df['DEPARTMENT_ID'].isin([60,90])]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,23.0,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,23.0,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,23.0,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,23.0,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,23.0,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,23.0,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,23.0,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,23.0,103.0,60.0

# this logic is very very important

In [74]:
# find employee who works under department 60 and 90 and their salary must in range between(6000,10000)
emp_in = df['DEPARTMENT_ID'].isin([60,90]) & df['SALARY'].between(6000,10000)
df[emp_in]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,23.0,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,23.0,103.0,60.0

In [78]:
# find the employee detail who work in HR_REP job_id and salary between range between 5000,8000
new_emp = df['JOB_ID'].isin(['HR_REP']) & df['SALARY'].between(5000,8000)
df[new_emp]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
103,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,23.0,101.0,40.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,23.0,101.0,40.0

IN Class practice  work

In [81]:
df[(df['DEPARTMENT_ID'] == 60) | (df['DEPARTMENT_ID'] == 90)]

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,23.0,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,23.0,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,23.0,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,23.0,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,23.0,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,2005-06-25,IT_PROG,4800,23.0,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,2006-02-05,IT_PROG,4800,23.0,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,2007-02-07,IT_PROG,4200,23.0,103.0,60.0

In [36]:
'''
1.data cleaning
2.feature  engineering
3.data analysis-python pandas & sql
4.data visualization->python vis /tableau
5.machine leanning,nlp,AI 

'''

'\n1.data cleaning\n2.feature  engineering\n3.data analysis-python pandas & sql\n4.data visualization->python vis /tableau\n5.machine leanning,nlp,AI \n\n\n\n'