In [1]:
import pandas as pd

# dataset df

In [2]:
df = pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/Employees.csv')
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [3]:
df.isnull().sum().sum()

np.int64(78)

In [4]:
val_mean = int(df['MANAGER_ID'].mean())
print(val_mean)

124

In [5]:
#df['MANAGER_ID'].fillna(val_mean,inplace=True)

#df['MANAGER_ID'].fillna(val_mean, inplace=True)

In [6]:
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [7]:
# by default this  function remove all those row  which contain NaN
#df.dropna() #dropna =(axix= 0,how = 'any',inplace =false)->default'''

In [8]:
# This line of code remove all column which has NaN value
#df.dropna(axis =1,how = 'any',inplace = True)

In [9]:
# using drop 
#dropna()-> if need to change data pemanently change  inplace =  TRUE
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,515.123.4567,2003-06-17,AD_PRES,24000,NaN,NaN,90.0
1,101,Neena,Kochhar,NKOCHHAR,515.123.4568,2005-09-21,AD_VP,17000,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,2001-01-13,AD_VP,17000,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,2006-01-03,IT_PROG,9000,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,2007-05-21,IT_PROG,6000,NaN,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,515.123.7777,2002-06-07,HR_REP,6500,NaN,101.0,40.0
108,204,Hermann,Baer,HBAER,515.123.8888,2002-06-07,PR_REP,10000,NaN,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,515.123.8080,2002-06-07,AC_MGR,12008,NaN,101.0,110.0
110,206,William,Gietz,WGIETZ,515.123.8181,2002-06-07,AC_ACCOUNT,8300,NaN,205.0,110.0

In [10]:
'''axies => 0(row) and a(column)
how -> any/all
dropna =(axix= 0,how = 'any',inplace =false)->default'''

"axies => 0(row) and a(column)\nhow -> any/all\ndropna =(axix= 0,how = 'any',inplace =false)->default"

In [11]:
#df.dropna(axis = 1,how ='any',inplace= True)

In [12]:
# column remove garnu milxa
# row ni drop garnu milxa ki nae

In [13]:
# any -->it delect row /column if any one value is nana
# all-->it remove only those column or row which has all value nan

In [14]:
'''
numeric->mean median

'''

'\nnumeric->mean median\n\n'

In [15]:
#commision_ID -> mean median
#manager_id,deparment_id ->mode
commi_mean = df['COMMISSION_PCT'].mean()
[commi_mean ]

[np.float64(0.22285714285714284)]

In [16]:
round_comm = round(commi_mean,2)# integer /float
round_comm

np.float64(0.22)

In [17]:
# format to string
fmt_mean = f'{commi_mean:.2f}' 
fmt_mean

'0.22'

In [18]:
# filna(Inplace=  true)
df['COMMISSION_PCT'] = df['COMMISSION_PCT'].fillna(round_comm)

In [19]:
df['COMMISSION_PCT'].unique()

array([0.22, 0.4 , 0.3 , 0.2 , 0.25, 0.15, 0.35, 0.1 ])

In [20]:
df['MANAGER_ID'].unique()

array([ nan, 100., 102., 103., 101., 108., 114., 120., 121., 122., 123.,
       124., 145., 146., 147., 148., 149., 201., 205.])

In [21]:
mang_mode = df['MANAGER_ID'].mode()
mang_mode

0    100.0
Name: MANAGER_ID, dtype: float64

In [22]:
dep_mode = df['DEPARTMENT_ID'].mode()[0]
dep_mode

np.float64(50.0)

In [23]:
df['DEPARTMENT_ID']= df['DEPARTMENT_ID'].fillna(dep_mode)

In [24]:
df['MANAGER_ID']= df['MANAGER_ID'].fillna(mang_mode)

In [25]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [26]:
# remove the dot from phone number
df['PHONE_NUMBER']= df['PHONE_NUMBER'].str.replace('.','', regex = False)
df

,EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPARTMENT_ID
0,100,Steven,King,SKING,5151234567,2003-06-17,AD_PRES,24000,0.22,100.0,90.0
1,101,Neena,Kochhar,NKOCHHAR,5151234568,2005-09-21,AD_VP,17000,0.22,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,5151234569,2001-01-13,AD_VP,17000,0.22,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,5904234567,2006-01-03,IT_PROG,9000,0.22,102.0,60.0
4,104,Bruce,Ernst,BERNST,5904234568,2007-05-21,IT_PROG,6000,0.22,103.0,60.0
...,...,...,...,...,...,...,...,...,...,...,...
106,206,William,Gietz,WGIETZ,5151238181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0
107,203,Susan,Mavris,SMAVRIS,5151237777,2002-06-07,HR_REP,6500,0.22,101.0,40.0
108,204,Hermann,Baer,HBAER,5151238888,2002-06-07,PR_REP,10000,0.22,101.0,70.0
109,205,Shelley,Higgins,SHIGGINS,5151238080,2002-06-07,AC_MGR,12008,0.22,101.0,110.0
110,206,William,Gietz,WGIETZ,5151238181,2002-06-07,AC_ACCOUNT,8300,0.22,205.0,110.0

## Data cleaning  perform on DF2

In [27]:
df2 = pd.read_csv("C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/Fraud Detection Dataset.csv")
df2

,Transaction_ID,User_ID,Transaction_Amount,Transaction_Type,Time_of_Transaction,Device_Used,Location,Previous_Fraudulent_Transactions,Account_Age,Number_of_Transactions_Last_24H,Payment_Method,Fraudulent
0,T1,4174,1292.76,ATM Withdrawal,16.0,Tablet,San Francisco,0,119,13,Debit Card,0
1,T2,4507,1554.58,ATM Withdrawal,13.0,Mobile,New York,4,79,3,Credit Card,0
2,T3,1860,2395.02,ATM Withdrawal,NaN,Mobile,NaN,3,115,9,NaN,0
3,T4,2294,100.10,Bill Payment,15.0,Desktop,Chicago,4,3,4,UPI,0
4,T5,2130,1490.50,POS Payment,19.0,Mobile,San Francisco,2,57,7,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...
50995,T33982,2339,3112.51,Bill Payment,15.0,Mobile,New York,0,7,8,Debit Card,0
50996,T31261,2152,2897.15,Online Purchase,3.0,Mobile,Miami,1,75,11,Net Banking,1
50997,T12293,3345,2204.43,POS Payment,18.0,Mobile,San Francisco,3,73,5,Credit Card,0
50998,T42287,1518,4787.17,POS Payment,19.0,Tablet,New York,2,108,14,Net Banking,0
50999,T13665,2315,814.72,POS Payment,3.0,Tablet,Los Angeles,0,50,10,Invalid Method,0

In [28]:
df2.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                  2520
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                         2473
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [29]:
df2['Transaction_Amount'].count()

np.int64(48480)

In [30]:
df2['Transaction_Amount'].mean()
# df2['Transaction_Amount'].median()

np.float64(2996.249784447195)

In [31]:
x= df2['Transaction_Amount'].median()

In [32]:
df2['Transaction_Amount']= df2['Transaction_Amount'].fillna(x)

In [33]:
df2['Device_Used'].unique()

<StringArray>
['Tablet', 'Mobile', 'Desktop', nan, 'Unknown Device']
Length: 5, dtype: str

In [34]:
dx = df2['Device_Used'].mode()
dx

0    Desktop
Name: Device_Used, dtype: str

In [35]:
df2['Device_Used']=df2['Device_Used'].fillna('Unknown Device')

In [36]:
df2.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                 2552
Device_Used                            0
Location                            2547
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

In [37]:
df2['Time_of_Transaction'].unique()

array([16., 13., nan, 15., 19.,  2.,  3., 20.,  0., 12., 21., 14.,  7.,
        4., 17., 10.,  5.,  8., 11., 18.,  1., 22.,  9.,  6., 23.])

In [38]:
tx = df2['Time_of_Transaction'].unique()
tx

array([16., 13., nan, 15., 19.,  2.,  3., 20.,  0., 12., 21., 14.,  7.,
        4., 17., 10.,  5.,  8., 11., 18.,  1., 22.,  9.,  6., 23.])

In [39]:
df2['Time_of_Transaction']=df2['Time_of_Transaction'].fillna('0')

In [40]:
df2['Location'].unique()

<StringArray>
['San Francisco',      'New York',             nan,       'Chicago',
        'Boston',       'Houston',         'Miami',   'Los Angeles',
       'Seattle']
Length: 9, dtype: str

In [41]:
ld = df2['Location'].mode()
ld

0    Boston
Name: Location, dtype: str

In [42]:
df2['Location'] = df2['Location'].fillna('Boston')
df2['Location']

0        San Francisco
1             New York
2               Boston
3              Chicago
4        San Francisco
             ...
50995         New York
50996            Miami
50997    San Francisco
50998         New York
50999      Los Angeles
Name: Location, Length: 51000, dtype: str

In [43]:
df2.isnull().sum()

Transaction_ID                         0
User_ID                                0
Transaction_Amount                     0
Transaction_Type                       0
Time_of_Transaction                    0
Device_Used                            0
Location                               0
Previous_Fraudulent_Transactions       0
Account_Age                            0
Number_of_Transactions_Last_24H        0
Payment_Method                      2469
Fraudulent                             0
dtype: int64

## In df2  all null value is removed

In [44]:
df2['Payment_Method'].unique()

<StringArray>
['Debit Card', 'Credit Card', nan, 'UPI', 'Net Banking', 'Invalid Method']
Length: 6, dtype: str

In [45]:
pay_mod = df2['Payment_Method'].mode()
pay_mod

0    UPI
Name: Payment_Method, dtype: str

In [46]:
df2['Payment_Method'] = df2['Payment_Method'].fillna('Invalid Method')

In [47]:
df2.isnull().sum()

Transaction_ID                      0
User_ID                             0
Transaction_Amount                  0
Transaction_Type                    0
Time_of_Transaction                 0
Device_Used                         0
Location                            0
Previous_Fraudulent_Transactions    0
Account_Age                         0
Number_of_Transactions_Last_24H     0
Payment_Method                      0
Fraudulent                          0
dtype: int64

In [48]:
'''
df and df2 in both dataset null value is totally removed 
'''

'\ndf and df2 in both dataset null value is totally removed \n'

## day6 --

In [49]:
# remove unwanted character
#@$%$#@@ -->regx(regular expression)

## day6 
# remove unwanted  character
# @$%$#@@ -->regx(regular expression)

In [50]:
df3 = pd.read_csv("C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/HR_Dataset Refresh.csv")
df3.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='str')

In [51]:
#using map function for formatting the salary column
df3['Salary'] = df3['Salary'].map('rs.{:,.2f}'.format)

In [52]:
df3

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,"rs.62,506.00",...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,"rs.104,437.00",...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,"rs.64,955.00",...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,"rs.64,991.00",...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,"rs.50,825.00",...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,"rs.50,825.00",...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2
578,Anderson Linda,10002,0,0,0,1,5,4,0,"rs.57,568.00",...,Amy Dunn,11.0,LinkedIn,Exceeds,5.00,5,0,1/7/2019,0,15
579,Andreola Colby,10194,0,0,0,1,4,3,0,"rs.95,660.00",...,Alex Sweetwater,10.0,LinkedIn,Fully Meets,3.04,3,4,1/2/2019,0,19
580,Athwal Sam,10062,0,4,1,1,5,3,0,"rs.59,365.00",...,Ketsia Liebig,19.0,Employee Referral,Fully Meets,5.00,4,0,2/25/2019,0,19
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,"rs.47,837.00",...,Brannon Miller,12.0,Diversity Job Fair,Fully Meets,4.46,3,0,1/25/2019,0,4

In [53]:
#df3['DateofTermination'].

In [54]:
df3.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
dtype: int64

# use replace function for removing unwanted data and replacing if from 
# replace function (find,replace,regex)

In [55]:
# remove unwanted data from data set
# Replace function is used for removing unwanted data and replacing it from valid text or space
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    str
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    str
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    str
 13  State                       582 non-null    str
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    str
 16  Gender                      582 non-null    str
 17  MaritalDesc                 582 non-null    str
 18  CitizenDesc                 582 non-null    str
 19  HispanicLatino              582 non-null    str
 20  RaceDesc                    582 non-null    str
 21  DateofHire                  582 non-null    str
 22  DateofTermination           196 non-null    str
 23  TermReason                  582 non-null    str
 24  EmploymentStatus            582 non-null    str
 25  Department                  582 non-null    str
 26  ManagerName                 582 non-null    str
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    str
 29  PerformanceScore            582 non-null    str
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    str
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(15), str(19)
memory usage: 163.8 KB

In [56]:
df3.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,"rs.62,506.00",...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,"rs.104,437.00",...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,"rs.64,955.00",...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,"rs.64,991.00",...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,"rs.50,825.00",...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

In [57]:
# replace(find,replace_value,regex=False) in default regex is True ,but if we want to change or replace then make false
# regex-->(,..@32$%+*)

df3['Employee_Name']= df3['Employee_Name'].str.replace(',',' ', regex = False)

In [58]:
df3.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,"rs.62,506.00",...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,"rs.104,437.00",...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,"rs.64,955.00",...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,"rs.64,991.00",...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,"rs.50,825.00",...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

remove unwanted white-space

In [59]:
# remove unwanted white-space
# categorical record
df3.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences'],
      dtype='str')

In [60]:
# categorical
columns = ['Position', 'State', 'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino','RaceDesc',
           'TermReason','EmploymentStatus','Department','RecruitmentSource']

for col in columns:
    u_col = df3[col].unique()
    print(col)
    print("-"*50)
    print(f'{u_col}\n')

Position
--------------------------------------------------
<StringArray>
[     'Production Technician I',                      'Sr. DBA',
     'Production Technician II',            'Software Engineer',
                   'IT Support',                 'Data Analyst',
       'Database Administrator',         'Enterprise Architect',
               'Sr. Accountant',           'Production Manager',
                 'Accountant I',           'Area Sales Manager',
 'Software Engineering Manager',                  'BI Director',
       'Director of Operations',         'Sr. Network Engineer',
                'Sales Manager',                 'BI Developer',
         'IT Manager - Support',             'Network Engineer',
                  'IT Director',            'Director of Sales',
     'Administrative Assistant',              'President & CEO',
          'Senior BI Developer',      'Shared Services Manager',
           'IT Manager - Infra',     'Principal Data Architect',
               'Data Architect',              'IT Manager - DB',
                'Data Analyst ',                          'CIO']
Length: 32, dtype: str

State
--------------------------------------------------
<StringArray>
['MA', 'TX', 'CT', 'VA', 'VT', 'AL', 'WA', 'CA', 'OH', 'IN', 'TN', 'NH', 'RI',
 'PA', 'CO', 'NY', 'UT', 'GA', 'FL', 'NC', 'KY', 'ID', 'NV', 'MT', 'OR', 'ND',
 'AZ', 'ME']
Length: 28, dtype: str

Gender
--------------------------------------------------
<StringArray>
['M ', 'F']
Length: 2, dtype: str

MaritalDesc
--------------------------------------------------
<StringArray>
['Single', 'Married', 'Divorced', 'Widowed', 'Separated']
Length: 5, dtype: str

CitizenDesc
--------------------------------------------------
<StringArray>
['US Citizen', 'Eligible NonCitizen', 'Non-Citizen']
Length: 3, dtype: str

HispanicLatino
--------------------------------------------------
<StringArray>
['No', 'Yes', 'no', 'yes']
Length: 4, dtype: str

RaceDesc
--------------------------------------------------
<StringArray>
[                           'White',        'Black or African American',
                'Two or more races',                            'Asian',
 'American Indian or Alaska Native',                         'Hispanic']
Length: 6, dtype: str

TermReason
--------------------------------------------------
<StringArray>
[               'N/A-StillEmployed',                    'career change',
                            'hours',                 'return to school',
                 'Another position',                          'unhappy',
                       'attendance',                      'performance',
    'Learned that he is a gangster',                         'retiring',
           'relocation out of area',                       'more money',
                         'military',                 'no-call, no-show',
                 'Fatal attraction', 'maternity leave - did not return',
                   'medical issues',                 'gross misconduct']
Length: 18, dtype: str

EmploymentStatus
--------------------------------------------------
<StringArray>
['Active', 'Voluntarily Terminated', 'Terminated for Cause']
Length: 3, dtype: str

Department
--------------------------------------------------
<StringArray>
[   'Production       ',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str

RecruitmentSource
--------------------------------------------------
<StringArray>
[               'LinkedIn',                  'Indeed',
           'Google Search',       'Employee Referral',
      'Diversity Job Fair', 'On-line Web application',
           'CareerBuilder',                 'Website',
                   'Other']
Length: 9, dtype: str

In [61]:
#strip() --> which is used for removing extra spece
strip_columns =['Position','Gender','Department']
for st_col in strip_columns:
    df3[st_col] = df3[st_col].str.strip()

In [62]:
# df3['Position'].unique()
#df3['Gender'].unique()
df3['Department'].unique()

<StringArray>
[          'Production',                'IT/IS', 'Software Engineering',
        'Admin Offices',                'Sales',     'Executive Office']
Length: 6, dtype: str

# Lable encoding

In [63]:
df3['HispanicLatino'] = (
    df3['HispanicLatino']
    .astype(str)          # convert to string
    .str.strip()          # remove spaces
    .str.lower()          # normalize case
    .map({'yes': 'Yes', 'no': 'No'})
)

In [64]:
df3['HispanicLatino'].unique() # reason behind to show nan

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [65]:
# hispanic latino
hl_data = {
    'No':'No',
    'Yes':'Yes',
    'no':'No',
    'yes':'Yes'
 }
df3['HispanicLatino'] = df3['HispanicLatino'].map(hl_data)

In [66]:
df3['HispanicLatino'].unique() # reason behind to show nan

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [67]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    str
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    str
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    str
 13  State                       582 non-null    str
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    str
 16  Gender                      582 non-null    str
 17  MaritalDesc                 582 non-null    str
 18  CitizenDesc                 582 non-null    str
 19  HispanicLatino              582 non-null    str
 20  RaceDesc                    582 non-null    str
 21  DateofHire                  582 non-null    str
 22  DateofTermination           196 non-null    str
 23  TermReason                  582 non-null    str
 24  EmploymentStatus            582 non-null    str
 25  Department                  582 non-null    str
 26  ManagerName                 582 non-null    str
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    str
 29  PerformanceScore            582 non-null    str
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    str
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(2), int64(15), str(19)
memory usage: 163.8 KB

In [68]:
mgr_mode = df3['ManagerID'].mode()[0]

In [69]:
df3['ManagerID'] = df3['ManagerID'].fillna(mgr_mode)

In [70]:
df3['ManagerID'] = df3['ManagerID'].astype(int)

In [71]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 36 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    str
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    str
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    str
 13  State                       582 non-null    str
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    str
 16  Gender                      582 non-null    str
 17  MaritalDesc                 582 non-null    str
 18  CitizenDesc                 582 non-null    str
 19  HispanicLatino              582 non-null    str
 20  RaceDesc                    582 non-null    str
 21  DateofHire                  582 non-null    str
 22  DateofTermination           196 non-null    str
 23  TermReason                  582 non-null    str
 24  EmploymentStatus            582 non-null    str
 25  Department                  582 non-null    str
 26  ManagerName                 582 non-null    str
 27  ManagerID                   582 non-null    int64
 28  RecruitmentSource           582 non-null    str
 29  PerformanceScore            582 non-null    str
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    str
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
dtypes: float64(1), int64(16), str(19)
memory usage: 163.8 KB

In [72]:

# formate oprion in mutiple formate 

'''
---------------------
format(parameter)
----------------------
'%d.%m.%Y'-default
'%d-%M-%Y'  
'mixed'


datfirst = true (default =  false)
change formate -> 'Y-M-D'
'''

"\n---------------------\nformat(parameter)\n----------------------\n'%d.%m.%Y'-default\n'%d-%M-%Y'  \n'mixed'\n\n\ndatfirst = true (default =  false)\nchange formate -> 'Y-M-D'\n"

In [73]:
df3['DOB'] = pd.to_datetime(df3['DOB'])

In [74]:
df3['DOB']

0     1983-07-10
1     1975-05-05
2     1988-09-19
3     1988-09-27
4     1989-09-08
         ...
577   1989-09-08
578   1977-05-22
579   1979-05-24
580   1983-02-18
581   1970-02-11
Name: DOB, Length: 582, dtype: datetime64[us]

In [75]:
df.isnull().sum()

EMPLOYEE_ID       0
FIRST_NAME        0
LAST_NAME         0
EMAIL             0
PHONE_NUMBER      0
HIRE_DATE         0
JOB_ID            0
SALARY            0
COMMISSION_PCT    0
MANAGER_ID        0
DEPARTMENT_ID     0
dtype: int64

In [76]:
df['HIRE_DATE'] = pd.to_datetime(df['HIRE_DATE'],format ='mixed')

In [77]:
df['HIRE_DATE']

0     2003-06-17
1     2005-09-21
2     2001-01-13
3     2006-01-03
4     2007-05-21
         ...
106   2002-06-07
107   2002-06-07
108   2002-06-07
109   2002-06-07
110   2002-06-07
Name: HIRE_DATE, Length: 111, dtype: datetime64[us]

In [78]:
# assignment about split function which is also one of the string function
# import re
#re.sub()
# explain about regular expression

# how we use split in this

In [79]:
text = "Data science is fun"
result = text.split()
print(result)

['Data', 'science', 'is', 'fun']

In [80]:
pinkidata = "my name is pinki and i am learning data science now, but i also interested in machine learning"
result = pinkidata.split(" ", 3)
print(result)

['my', 'name', 'is', 'pinki and i am learning data science now, but i also interested in machine learning']