In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/Data/Data/HR_Dataset Refresh.csv')
df.head()

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Michael Albert,22.0,LinkedIn,Exceeds,4.60,5,0,1/17/2019,0,1
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Simon Roup,4.0,Indeed,Fully Meets,4.96,3,6,2/24/2016,0,17
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Kissy Sullivan,20.0,LinkedIn,Fully Meets,3.02,3,0,5/15/2012,0,3
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Elijiah Gray,16.0,Indeed,Fully Meets,4.84,5,0,1/3/2019,0,15
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Webster Butler,39.0,Google Search,Fully Meets,5.00,4,0,2/1/2016,0,2

Formate_of_naming
Last_name/First_Name/Middle_Name

In [3]:
df['Employee_Name']

0           Adinolfi  Wilson  K
1      Ait Sidi  Karthikeyan
2             Akinkuolie  Sarah
3                  Alagbe Trina
4              Anderson  Carol
                 ...
577            Anderson  Carol
578           Anderson  Linda
579             Andreola  Colby
580                 Athwal  Sam
581            Bachiochi  Linda
Name: Employee_Name, Length: 582, dtype: str

# split function

In [4]:
# split employee name to first_name ,middle_name and last_name   
#split(find,n = index,expand = True)
#df[['First_Name','middle_Name','Last_Name']] = df['Employee_Name'].str.split(' ',n = 2,expand = True)

In [5]:
#df= df.drop('Last_Name',axis = 1)

In [6]:
first_last  = df['Employee_Name'].str.split(' ', n=1, expand=True)
first_last

              0                     1
0      Adinolfi             Wilson  K
1           Ait  Sidi  Karthikeyan
2    Akinkuolie                 Sarah
3        Alagbe                 Trina
4      Anderson                Carol
..          ...                   ...
577    Anderson                Carol
578    Anderson               Linda
579    Andreola                 Colby
580      Athwal                   Sam
581   Bachiochi                 Linda

[582 rows x 2 columns]

In [7]:
middle_first = first_last[1].str.strip().str.split(' ',n= 1,expand = True)
middle_first

          0             1
0    Wilson             K
1      Sidi   Karthikeyan
2     Sarah           NaN
3     Trina           NaN
4     Carol           NaN
..      ...           ...
577   Carol           NaN
578   Linda           NaN
579   Colby           NaN
580     Sam           NaN
581   Linda           NaN

[582 rows x 2 columns]

In [8]:
# first_last[0] = Last_Name
# middle_first[0]= First_Name
# middle_first[1] = middle_name

In [9]:
middle_first
df['F_Name'] = middle_first[0]
df['M_Name'] = middle_first[1]
df['L_Name'] = first_last[0]

In [10]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,F_Name,M_Name,L_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,Sidi,Karthikeyan,Ait
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,Sarah,NaN,Akinkuolie
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Carol,NaN,Anderson
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,Linda,NaN,Anderson
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,Colby,NaN,Andreola
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,Sam,NaN,Athwal
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,Linda,NaN,Bachiochi

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    str
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    str
 13  State                       582 non-null    str
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    str
 16  Gender                      582 non-null    str
 17  MaritalDesc                 582 non-null    str
 18  CitizenDesc                 582 non-null    str
 19  HispanicLatino              582 non-null    str
 20  RaceDesc                    582 non-null    str
 21  DateofHire                  582 non-null    str
 22  DateofTermination           196 non-null    str
 23  TermReason                  582 non-null    str
 24  EmploymentStatus            582 non-null    str
 25  Department                  582 non-null    str
 26  ManagerName                 582 non-null    str
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    str
 29  PerformanceScore            582 non-null    str
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    str
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
 36  F_Name                      582 non-null    str
 37  M_Name                      76 non-null     str
 38  L_Name                      582 non-null    str
dtypes: float64(2), int64(16), str(21)
memory usage: 177.5 KB

In [12]:
# python -> string
# numpy -> <U7
# pandas -> object
# date, time -> datetime
# datetime datatype -> pandas

In [13]:
'''
Date
-----------------------
format
--------
'%d.%m.%y' -> default
'%d-%m-%y'
mixed

dayfirst=False -> default
dayfirst=True
---------------------
After convert -> Year-Month-Day

Time
----------
---- Hour Minute Second
'%H.%M.%S' -> default
'%H-%M-%S'
mixed

After convert -> Today date Hour:Minute:Second
'''

"\nDate\n-----------------------\nformat\n--------\n'%d.%m.%y' -> default\n'%d-%m-%y'\nmixed\n\ndayfirst=False -> default\ndayfirst=True\n---------------------\nAfter convert -> Year-Month-Day\n\nTime\n----------\n---- Hour Minute Second\n'%H.%M.%S' -> default\n'%H-%M-%S'\nmixed\n\nAfter convert -> Today date Hour:Minute:Second\n"

In [14]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'F_Name', 'M_Name', 'L_Name'],
      dtype='str')

In [15]:
# to convert into date time -> to_datetime(date_column)
df['DOB'] = pd.to_datetime(df['DOB'], format='mixed')

In [16]:
df['DateofHire'] = pd.to_datetime(df['DateofHire'])

In [17]:
df['DateofTermination'] = pd.to_datetime(df['DateofTermination'])
# generally we can not fill with any value in dateoftermination ,Keep it as NaN (BEST option)-because
# ❌ Don’t use mode
# ✅ Keep NaN OR create status column
# ✅ Treat it as event-based

In [18]:
df['DateofTermination']

0            NaT
1     2016-06-16
2     2012-09-24
3            NaT
4     2016-09-06
         ...
577   2016-09-06
578          NaT
579          NaT
580          NaT
581          NaT
Name: DateofTermination, Length: 582, dtype: datetime64[us]

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 582 entries, 0 to 581
Data columns (total 39 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Employee_Name               582 non-null    str
 1   EmpID                       582 non-null    int64
 2   MarriedID                   582 non-null    int64
 3   MaritalStatusID             582 non-null    int64
 4   GenderID                    582 non-null    int64
 5   EmpStatusID                 582 non-null    int64
 6   DeptID                      582 non-null    int64
 7   PerfScoreID                 582 non-null    int64
 8   FromDiversityJobFairID      582 non-null    int64
 9   Salary                      582 non-null    int64
 10  Termd                       582 non-null    int64
 11  PositionID                  582 non-null    int64
 12  Position                    582 non-null    str
 13  State                       582 non-null    str
 14  Zip                         582 non-null    int64
 15  DOB                         582 non-null    datetime64[us]
 16  Gender                      582 non-null    str
 17  MaritalDesc                 582 non-null    str
 18  CitizenDesc                 582 non-null    str
 19  HispanicLatino              582 non-null    str
 20  RaceDesc                    582 non-null    str
 21  DateofHire                  582 non-null    datetime64[us]
 22  DateofTermination           196 non-null    datetime64[us]
 23  TermReason                  582 non-null    str
 24  EmploymentStatus            582 non-null    str
 25  Department                  582 non-null    str
 26  ManagerName                 582 non-null    str
 27  ManagerID                   574 non-null    float64
 28  RecruitmentSource           582 non-null    str
 29  PerformanceScore            582 non-null    str
 30  EngagementSurvey            582 non-null    float64
 31  EmpSatisfaction             582 non-null    int64
 32  SpecialProjectsCount        582 non-null    int64
 33  LastPerformanceReview_Date  582 non-null    str
 34  DaysLateLast30              582 non-null    int64
 35  Absences                    582 non-null    int64
 36  F_Name                      582 non-null    str
 37  M_Name                      76 non-null     str
 38  L_Name                      582 non-null    str
dtypes: datetime64[us](3), float64(2), int64(16), str(18)
memory usage: 177.5 KB

In [20]:
# Date of Termination -> Null
# After convert to date time -> NaT
# Do we need to clean it?

In [21]:
df

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,Salary,...,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30,Absences,F_Name,M_Name,L_Name
0,Adinolfi Wilson K,10026,0,0,1,1,5,4,0,62506,...,Exceeds,4.60,5,0,1/17/2019,0,1,Wilson,K,Adinolfi
1,Ait Sidi Karthikeyan,10084,1,1,1,5,3,3,0,104437,...,Fully Meets,4.96,3,6,2/24/2016,0,17,Sidi,Karthikeyan,Ait
2,Akinkuolie Sarah,10196,1,1,0,5,5,3,0,64955,...,Fully Meets,3.02,3,0,5/15/2012,0,3,Sarah,NaN,Akinkuolie
3,Alagbe Trina,10088,1,1,0,1,5,3,0,64991,...,Fully Meets,4.84,5,0,1/3/2019,0,15,Trina,NaN,Alagbe
4,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Carol,NaN,Anderson
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Anderson Carol,10069,0,2,0,5,5,3,0,50825,...,Fully Meets,5.00,4,0,2/1/2016,0,2,Carol,NaN,Anderson
578,Anderson Linda,10002,0,0,0,1,5,4,0,57568,...,Exceeds,5.00,5,0,1/7/2019,0,15,Linda,NaN,Anderson
579,Andreola Colby,10194,0,0,0,1,4,3,0,95660,...,Fully Meets,3.04,3,4,1/2/2019,0,19,Colby,NaN,Andreola
580,Athwal Sam,10062,0,4,1,1,5,3,0,59365,...,Fully Meets,5.00,4,0,2/25/2019,0,19,Sam,NaN,Athwal
581,Bachiochi Linda,10114,0,0,0,3,5,3,1,47837,...,Fully Meets,4.46,3,0,1/25/2019,0,4,Linda,NaN,Bachiochi

In [22]:
df.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
F_Name                          0
M_Name                        506
L_Name                          0
dtype: int64

In [23]:
df.to_csv('cleaned_hr_data',index=False)

In [24]:
data =pd.read_csv('C:/Users/pinki/OneDrive/Desktop/Data_science(infosis)/datascience_steps_daywise/cleaned_hr_data')

In [25]:
# explain

# Just For practice

In [26]:
# import pandas as pd

# df = pd.DataFrame({
#     'age': [18, 25, 35, 45, 60]
# })

In [27]:
'''# Normalization (Min-Max Scaling)MinMaxScaller
# It is a tool that scales values between 0 and 1
# 4. fit_transform()

# This does TWO things at once:

#  5.(a) fit()
# Learns from data
# Finds min and max values 
# 🔸 (b) transform()
Applies formula:

new value = x−min/Min-Max
# '''


# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# df['age_normalized'] = scaler.fit_transform(df[['age']])

# print(df)

'# Normalization (Min-Max Scaling)MinMaxScaller\n# It is a tool that scales values between 0 and 1\n# 4. fit_transform()\n\n# This does TWO things at once:\n\n#  5.(a) fit()\n# Learns from data\n# Finds min and max values \n# 🔸 (b) transform()\nApplies formula:\n\nnew value = x−min/Min-Max\n# '

In [29]:
df.columns

Index(['Employee_Name', 'EmpID', 'MarriedID', 'MaritalStatusID', 'GenderID',
       'EmpStatusID', 'DeptID', 'PerfScoreID', 'FromDiversityJobFairID',
       'Salary', 'Termd', 'PositionID', 'Position', 'State', 'Zip', 'DOB',
       'Gender', 'MaritalDesc', 'CitizenDesc', 'HispanicLatino', 'RaceDesc',
       'DateofHire', 'DateofTermination', 'TermReason', 'EmploymentStatus',
       'Department', 'ManagerName', 'ManagerID', 'RecruitmentSource',
       'PerformanceScore', 'EngagementSurvey', 'EmpSatisfaction',
       'SpecialProjectsCount', 'LastPerformanceReview_Date', 'DaysLateLast30',
       'Absences', 'F_Name', 'M_Name', 'L_Name'],
      dtype='str')

In [32]:
df['Hire_Year'] = df['DateofHire'].dt.year

In [34]:
df['Hire_month'] = df['DateofHire'].dt.month

In [35]:
df['Hire_day'] = df['DateofHire'].dt.day

In [37]:
# exttract name of month abd day
df['Hire_month name'] = df['DateofHire'].dt.month_name()
df['Hire_day_name'] = df['DateofHire'].dt.day_name()

In [39]:
df.isnull().sum()

Employee_Name                   0
EmpID                           0
MarriedID                       0
MaritalStatusID                 0
GenderID                        0
EmpStatusID                     0
DeptID                          0
PerfScoreID                     0
FromDiversityJobFairID          0
Salary                          0
Termd                           0
PositionID                      0
Position                        0
State                           0
Zip                             0
DOB                             0
Gender                          0
MaritalDesc                     0
CitizenDesc                     0
HispanicLatino                  0
RaceDesc                        0
DateofHire                      0
DateofTermination             386
TermReason                      0
EmploymentStatus                0
Department                      0
ManagerName                     0
ManagerID                       8
RecruitmentSource               0
PerformanceScore                0
EngagementSurvey                0
EmpSatisfaction                 0
SpecialProjectsCount            0
LastPerformanceReview_Date      0
DaysLateLast30                  0
Absences                        0
F_Name                          0
M_Name                        506
L_Name                          0
Hire_Year                       0
Hire_month                      0
Hire_day                        0
Hire_month name                 0
Hire_day_name                   0
dtype: int64

In [ ]:
'''mobile  phones

mobile : 0
mobile :1
mobile : 3



'''
df['']

In [40]:
df['HispanicLatino'].unique()

<StringArray>
['No', 'Yes', 'no', 'yes']
Length: 4, dtype: str

In [ ]:
hismap = {
    'no':'No',
    'yes':'Yes',
    'Yes':'Yes',
    'No':'No'
}

df['HispanicLatino'] = df['HispanicLatino'].map(hismap)

In [42]:
df['HispanicLatino'].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [43]:
hismap_id = {
    'No':0,
    'Yes':1
}
df['HispanicLatino']
df['HispanicLatino'] = df['HispanicLatino'].map(hismap_id)

In [44]:
df['HispanicLatino'].unique()

array([0, 1])

In [46]:
df['EmploymentStatus'].unique()

<StringArray>
['Active', 'Voluntarily Terminated', 'Terminated for Cause']
Length: 3, dtype: str

In [ ]:
emp_status ={
    'Active':0,
    'Voluntarily Terminated':1,
    'Terminated for Cause':2
}
df['empStatus_ID'] = df['EmploymentStatus'].map(emp_status)

In [53]:
df['empStatus_ID'].unique()

array([0, 1, 2])

In [54]:
df.to_csv('cleaned_data1',index = False)